backend:
  name: git-gateway
  branch: master
media_library:
  name: cloudinary
  config:
    cloud_name: prestocloud
    api_key: 875834652743413
collections:
  - name: pages
    label: Pages
    files:
      - label: Home
        name: home
        file: content/home.md
        fields:
          - {
              label: 'Hero main text',
              name: 'hero_main_text',
              widget: 'string',
            }
          - { label: 'Hero sub text', name: 'hero_sub_text', widget: 'string' }
          - {
              label: 'Audio sample text',
              name: 'audio_sample_text',
              widget: 'string',
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: Inquiries
        name: inquiries
        file: content/inquiries.md
        fields:
          - {
              label: 'Request field prompt',
              name: 'request_field_prompt',
              widget: string,
            }
          - {
              label: 'Attribution field prompt',
              name: 'attribution_field_prompt',
              widget: 'string',
            }
          - {
              label: 'Attribution field options',
              name: 'attribution_field_options',
              widget: 'list',
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: portfolio_categories
    label: Portfolio Categories
    folder: content/portfolio_categories
    create: true
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: priority
        label: Priority
        widget: number
        value_type: int
        step: 1000
        required: true
  - name: portfolio_items
    label: Portfolio Items
    folder: content/portfolio_items
    create: true
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: media_type
        label: Media Type
        widget: select
        options:
          - audio
          - video
        required: true
      - name: media_source
        label: Media
        widget: file
        required: true
      - name: thumbnail_source
        label: Thumbnail
        widget: image
        required: true
      - name: homepage_visible
        label: Visible on Homepage
        widget: boolean
        default: false
        required: true
      - name: priority
        label: Priority
        widget: number
        value_type: int
        step: 1000
        required: true
      - name: category
        label: Category
        widget: relation
        collection: portfolio_categories
        value_field: title
        search_fields:
          - title
        required: true
        options_length: 7
